spring:
  security:
    user:
      name: yasmani
      password: 123

  datasource:
    url: jdbc:postgresql://localhost:5432/exampledb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update     # para desarrollo; en producción usar migrations
    show-sql: true

app:
  jwt:
    secret: "01234567890123456789012345678901"